AWSTemplateFormatVersion: 2010-09-09
Description: IAC Cloudformation Template for Lambda Function creation

Parameters:
  Env:
    Type: String
    AllowedValues:
      - dev
      - hom
      - pro
  LambdaArn:
    Type: String

Resources:

  EventRuleExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "upador-arquivos-event-rule-execution-role-${Env}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  EventRuleExecutionRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "lambda-invoking-access-policy-for-event-rule-execution-${Env}"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource: !Ref LambdaArn
      Roles:
        - !Ref EventRuleExecutionRole

  EventRuleExecutionRolePolicyForLogs:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "logs-for-events-rule-execution-${Env}"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "*"
      Roles:
        - !Ref EventRuleExecutionRole