AWSTemplateFormatVersion: 2010-09-09
Description: IAC Cloudformation Template for Lambda Function creation

Parameters:
  Env:
    Type: String
    AllowedValues:
      - dev
      - hom
      - pro
  LambdaArn:
    Type: String
  AwsAccountId:
    Type: String

Resources:

  EventRuleExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "upador-arquivos-event-rule-execution-role-${Env}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  EventRuleExecutionRolePolicyForLambda:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "lambda-invoking-access-policy-for-event-rule-execution-${Env}"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource: !Ref LambdaArn
      Roles:
        - !Ref EventRuleExecutionRole

  EventRuleExecutionRolePolicyForEcs:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "ecs-task-invoking-access-policy-for-event-rule-execution-${Env}"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - ecs:RunTask
            Resource: '*'
          - Effect: Allow
            Action:
              - iam:PassRole
            Resource: '*'
            Condition:
              StringLike:
                iam:PassedToService: 'ecs-tasks.amazonaws.com'
          - Effect: Allow
            Action:
              - iam:PassRole
            Resource:
              - !Sub 'arn:aws:iam::${AwsAccountId}:role/upador-arquivos-ecs-task-execution-role-${Env}'
              - !Sub 'arn:aws:iam::${AwsAccountId}:role/upador-arquivos-ecs-task-role-${Env}'
          - Effect: Allow
            Action:
              - ecr:GetAuthorizationToken
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:CreateLogGroup
            Resource: '*'
      Roles:
        - !Ref EventRuleExecutionRole