AWSTemplateFormatVersion: 2010-09-09
Description: IAC Cloudformation Template for Lambda Function creation

Parameters:
  Env:
    Type: String
    AllowedValues:
      - dev
      - hom
      - pro

Resources:

  EcsTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "upador-arquivos-ecs-task-role-${Env}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  EcsTaskRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "upador-arquivos-ecs-task-role-policy-${Env}"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:DeleteObject
              - s3:GetObject
              - s3:ListBucket
              - s3:ListBuckets
            Resource: !Sub "arn:aws:s3:::julucin-bucket-salvar-arquivos-periodicamente-${Env}/*"
      Roles:
        - !Ref EcsTaskRole

  EcsTaskRolePolicyForLogs:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "logs-for-ecs-task-${Env}"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "*"
      Roles:
        - !Ref EcsTaskRole