AWSTemplateFormatVersion: 2010-09-09
Description: IAC Cloudformation Template for Lambda Function creation

Parameters:
  Env:
    Type: String
    AllowedValues:
      - dev
      - hom
      - pro
  EcsTaskArn:
    Type: String
  ExecutionRoleArn:
    Type: String
  ClusterUpadorArquivo:
    Type: String
Resources:

  UpadorArquivoTrigger:
    Type: AWS::Events::Rule
    Properties:
      Description: Event which will trigger the execution of the Lambda Function which uploads files to S3.
      Name: !Sub "upador-arquivo-trigger-${Env}"
      RoleArn: !Ref ExecutionRoleArn
      ScheduleExpression: rate(2 minutes)
      State: ENABLED
      Targets:
        - Arn: !Ref ClusterUpadorArquivo
          RoleArn: !Ref ExecutionRoleArn
          Id: UpadorArquivoTrigger
          EcsParameters:
            TaskCount: 1
            TaskDefinitionArn: !Ref EcsTaskArn
            LaunchType: FARGATE
            NetworkConfiguration:
              AwsVpcConfiguration:
                AssignPublicIp: ENABLED
                Subnets:
                  - subnet-03ef82be02885fb12
                  - subnet-094c66d797d1350f6