AWSTemplateFormatVersion: 2010-09-09
Description: IAC Cloudformation Template for ECS Cluster

Resources:

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      CapacityProviders:
        - FARGATE_SPOT
      ClusterName: upador-arquivos-cluster
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
